version: '3.8'
services:
  producer:
    build:
      context: .
      dockerfile: ./streamer/dockerfiles/Dockerfile.producer
    image: producer-app:latest
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=localhost:9092
    volumes:
      - ./data_lake:/app/data_lake
    # networks:
    #   - shared_network

  consumer:
    build:
      context: .
      dockerfile: ./streamer/dockerfiles/Dockerfile.consumer
    image: consumer-app:latest
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=localhost:9092
    command: "--start-date 2013-06-01 --end-date 2015-06-01 --longitude-min -74.0 --longitude-max -73.0 --latitude-min 40.5 --latitude-max 41.0"
    volumes:
      - ./streamer/data:/app/data
      - ./data_lake:/app/data_lake
    # networks:
    #   - shared_network

  # spark:
  #   build: ./spark/job  # TODO: Dockerfile for Spark in ./spark/job directory
  #   depends_on:
  #     - kafka

volumes:
  data_lake:

# networks:
#   shared_network:
#     external: true